[2025-05-01T13:07:11.705+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T13:07:11.731+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_files_to_snowflake.upload_files_to_snowflake manual__2025-05-01T13:01:42.620089+00:00 [queued]>
[2025-05-01T13:07:11.749+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_files_to_snowflake.upload_files_to_snowflake manual__2025-05-01T13:01:42.620089+00:00 [queued]>
[2025-05-01T13:07:11.750+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-01T13:07:11.772+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_files_to_snowflake> on 2025-05-01 13:01:42.620089+00:00
[2025-05-01T13:07:11.787+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'multi_files_to_snowflake', 'upload_files_to_snowflake', 'manual__2025-05-01T13:01:42.620089+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/to_snowflake.py', '--cfg-path', '/tmp/tmpve3ymm26']
[2025-05-01T13:07:11.795+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask upload_files_to_snowflake
[2025-05-01T13:07:11.798+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=131) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T13:07:11.799+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2025-05-01T13:07:11.876+0000] {task_command.py:467} INFO - Running <TaskInstance: multi_files_to_snowflake.upload_files_to_snowflake manual__2025-05-01T13:01:42.620089+00:00 [running]> on host 58f02bcfe274
[2025-05-01T13:07:12.231+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='multi_files_to_snowflake' AIRFLOW_CTX_TASK_ID='upload_files_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T13:01:42.620089+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T13:01:42.620089+00:00'
[2025-05-01T13:07:12.233+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-01T13:07:12.279+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-05-01T13:07:12.379+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-05-01T13:07:12.381+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-01T13:07:12.382+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-01T13:07:14.599+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/to_snowflake.py", line 41, in upload_files_to_snowflake
    df.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1948, in to_sql
    table = self.prep_table(
            ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1852, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 929, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1999, in drop_table
    self.meta.reflect(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 4889, in reflect
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(snowflake://AYOUB:***@gkexgfn-mc38946/VOITURE_DATA/PUBLIC?application=AIRFLOW&authenticator=snowflake&role=ACCOUNTADMIN&warehouse=COMPUTE_WH) schema 'PUBLIC': (ELECTRI0)
[2025-05-01T13:07:14.644+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=multi_files_to_snowflake, task_id=upload_files_to_snowflake, run_id=manual__2025-05-01T13:01:42.620089+00:00, execution_date=20250501T130142, start_date=20250501T130711, end_date=20250501T130714
[2025-05-01T13:07:14.689+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-01T13:07:14.690+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task upload_files_to_snowflake (Could not reflect: requested table(s) not available in Engine(snowflake://AYOUB:***@gkexgfn-mc38946/VOITURE_DATA/PUBLIC?application=AIRFLOW&authenticator=snowflake&role=ACCOUNTADMIN&warehouse=COMPUTE_WH) schema 'PUBLIC': (ELECTRI0); 144)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/to_snowflake.py", line 41, in upload_files_to_snowflake
    df.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1948, in to_sql
    table = self.prep_table(
            ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1852, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 929, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1999, in drop_table
    self.meta.reflect(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 4889, in reflect
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(snowflake://AYOUB:***@gkexgfn-mc38946/VOITURE_DATA/PUBLIC?application=AIRFLOW&authenticator=snowflake&role=ACCOUNTADMIN&warehouse=COMPUTE_WH) schema 'PUBLIC': (ELECTRI0)
[2025-05-01T13:07:14.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-01T13:07:14.770+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T13:07:14.772+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
